models:
  backbone: resnet18
  pretrained: true

data:
  dataset: AADB
  image_dir: data/aadb/images
  labels_dir: data/aadb/labels
  num_attributes: 12
  input_shape: [256, 256]
  batch_size: 32

train:
  epochs: 5
  lr: 3E-4
  momentum: 0.9
  margin: 0.02
  num_prefetch: 8
  log_interval: 10
  save_dir: models/ #/content/drive/MyDrive/Github/pointnet-pytorch/models
  
device: cuda
